version: '3.8'

services:
  nest-api-app:
    build: .
    extra_hosts:
        - "host.docker.internal:host-gateway"
    container_name: nest-api-app
    ports:
      - "${PORT}:3000"
    restart: always
    env_file:
      - .env
